// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwGbt10qpcfZAuulnPm5ajSfwhncyMSjo',
    appId: '1:863970286905:web:55d042afd7879d35c55ce8',
    messagingSenderId: '863970286905',
    projectId: 'deshi-mart-34518',
    authDomain: 'deshi-mart-34518.firebaseapp.com',
    storageBucket: 'deshi-mart-34518.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0dxXmaY2P9SlzCZgMHz7D-m7y1H6zG-4',
    appId: '1:863970286905:android:aa2c71685c3da044c55ce8',
    messagingSenderId: '863970286905',
    projectId: 'deshi-mart-34518',
    storageBucket: 'deshi-mart-34518.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7YBwJNwed822ZEQQyKNfyUGS-HAeLrzo',
    appId: '1:863970286905:ios:055735e9c327d18fc55ce8',
    messagingSenderId: '863970286905',
    projectId: 'deshi-mart-34518',
    storageBucket: 'deshi-mart-34518.firebasestorage.app',
    iosBundleId: 'com.example.deshiMart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7YBwJNwed822ZEQQyKNfyUGS-HAeLrzo',
    appId: '1:863970286905:ios:055735e9c327d18fc55ce8',
    messagingSenderId: '863970286905',
    projectId: 'deshi-mart-34518',
    storageBucket: 'deshi-mart-34518.firebasestorage.app',
    iosBundleId: 'com.example.deshiMart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwGbt10qpcfZAuulnPm5ajSfwhncyMSjo',
    appId: '1:863970286905:web:c449aa1ff8c909d7c55ce8',
    messagingSenderId: '863970286905',
    projectId: 'deshi-mart-34518',
    authDomain: 'deshi-mart-34518.firebaseapp.com',
    storageBucket: 'deshi-mart-34518.firebasestorage.app',
  );

}